
import { UserStats, Persona, LanguageCode, AIModel } from "./types";

export const INITIAL_STATS: UserStats = {
  sessionsCompleted: 0,
  nodesExplored: 0,
  minutesDebated: 0,
  quizScore: 0,
  weeklyActivity: [
    { day: 'Mon', value: 0 },
    { day: 'Tue', value: 0 },
    { day: 'Wed', value: 0 },
    { day: 'Thu', value: 0 },
    { day: 'Fri', value: 0 },
    { day: 'Sat', value: 0 },
    { day: 'Sun', value: 0 },
  ],
  level: 1,
  title: "Novice Explorer"
};

export const AI_MODELS: AIModel[] = [
    { 
        id: 'gemini-2.5-flash', 
        name: 'Gemini 2.5 Flash', 
        provider: 'GOOGLE', 
        description: 'Fastest, Efficient (Default)',
        icon: 'Zap',
        isPro: false 
    },
    { 
        id: 'gemini-3-pro-preview', 
        name: 'Gemini 3.0 Pro', 
        provider: 'GOOGLE', 
        description: 'Deep Reasoning & Logic',
        icon: 'Brain',
        isPro: true 
    },
    { 
        id: 'gemini-flash-lite-latest', 
        name: 'Gemini Flash Lite', 
        provider: 'GOOGLE', 
        description: 'Lightweight & Ultra-Fast',
        icon: 'Feather',
        isPro: false 
    },
    { 
        id: 'gpt-4o', 
        name: 'GPT-4o', 
        provider: 'OPENAI', 
        description: 'OpenAI Flagship (Demo)',
        icon: 'Sparkles',
        isPro: true 
    },
    { 
        id: 'claude-3-5-sonnet', 
        name: 'Claude 3.5 Sonnet', 
        provider: 'ANTHROPIC', 
        description: 'Anthropic Intelligence (Demo)',
        icon: 'Brain',
        isPro: true 
    }
];

export const IMAGE_MODELS: AIModel[] = [
    {
        id: 'gemini-2.5-flash-image',
        name: 'Aetheris Standard',
        provider: 'GOOGLE', 
        description: 'Fast Generation (Default)',
        isPro: false
    },
    {
        id: 'gemini-3-pro-image-preview',
        name: 'Aetheris HD Pro',
        provider: 'GOOGLE',
        description: 'High Definition Detail',
        isPro: true
    }
];

export const PERSONAS: Persona[] = [
    {
        id: 'sage',
        name: 'The Sage',
        role: 'Philosopher',
        description: 'Deep wisdom & metaphors.',
        systemInstruction: 'You are a wise philosopher. Speak with depth, use metaphors, and encourage contemplation.',
        voiceName: 'Kore',
        color: 'from-amber-400 to-orange-500'
    },
    {
        id: 'futurist',
        name: 'The Futurist',
        role: 'Tech Visionary',
        description: 'Optimistic about tomorrow.',
        systemInstruction: 'You are a futurist. Speak with excitement about technology and the future.',
        voiceName: 'Fenrir',
        color: 'from-cyan-400 to-blue-500'
    },
    {
        id: 'skeptic',
        name: 'The Skeptic',
        role: 'Critical Thinker',
        description: 'Challenges assumptions.',
        systemInstruction: 'You are a critical thinker. Challenge assumptions and ask probing questions.',
        voiceName: 'Puck',
        color: 'from-rose-400 to-red-500'
    },
    {
        id: 'guide',
        name: 'The Guide',
        role: 'Mentor',
        description: 'Supportive and clear.',
        systemInstruction: 'You are a helpful mentor. Explain concepts clearly and patiently.',
        voiceName: 'Charon',
        color: 'from-emerald-400 to-teal-500'
    }
];

export const LANGUAGES: { code: LanguageCode; name: string; flag: string }[] = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
    { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' }
];

export const LANGUAGE_PROMPT_NAMES: Record<LanguageCode, string> = {
    en: 'English',
    bn: 'Bengali',
    es: 'Spanish',
    fr: 'French',
    hi: 'Hindi'
};

export const IMAGE_STYLES = [
  { id: 'cinematic', label: 'Cinematic' },
  { id: 'digital-art', label: 'Digital Art' },
  { id: 'surreal', label: 'Surrealism' },
  { id: '3d-render', label: '3D Render' },
  { id: 'sketch', label: 'Pencil Sketch' },
  { id: 'cyberpunk', label: 'Cyberpunk' }
];

export const SKILL_CATEGORIES = [
    { id: 'communication', label: 'Communication', icon: 'MessageCircle', desc: 'Master difficult conversations & negotiation.' },
    { id: 'reasoning', label: 'Logical Reasoning', icon: 'BrainCircuit', desc: 'Solve complex deductive puzzles.' },
    { id: 'problem_solving', label: 'Hard Problem Solving', icon: 'Puzzle', desc: 'Tackle high-constraint scenarios.' },
    { id: 'leadership', label: 'Leadership', icon: 'Flag', desc: 'Team management & decision making.' },
    { id: 'emotional_intelligence', label: 'Emotional IQ', icon: 'Heart', desc: 'Empathy & social awareness.' }
];

export const TRANSLATIONS = {
    en: {
        dashboard: "Command Center",
        neuroMap: "Neuro Graph",
        mindMeld: "Mind Meld",
        visionLab: "Vision Lab",
        quantumQuiz: "Quantum Quiz",
        nexusChat: "Nexus Chat",
        cosmosLearn: "Cosmos Learn",
        ideaVault: "Idea Vault",
        mathPath: "Infinity Math",
        skillForge: "Skill Forge",
        codeNexus: "Code Nexus",
        sessions: "Sessions Run",
        concepts: "Concepts Mapped",
        debateTime: "Debate Time",
        quizXp: "Quiz XP",
        welcome: "Neural Interface Ready",
        welcomeSub: "Your cognitive journey begins now.",
        systemStatus: "System Status",
        expandGraph: "Expand Knowledge Graph",
        resetApp: "Factory Reset App",
        startTopic: "Start with a topic...",
        addConcept: "Add concept...",
        expandNode: "Expand This Node",
        selectPersona: "Select Persona",
        liveLink: "Live Link Active",
        initLink: "Initialize Link",
        listening: "The AI is listening. Speak clearly.",
        connectToStart: "Select a persona and connect to begin.",
        visualGen: "Visual Metaphor Generator",
        visualDesc: "Convert abstract theories into concrete visual art.",
        conceptLabel: "Concept to Visualize",
        generateBtn: "Generate Visualization",
        quizTitle: "Quantum Quiz",
        quizDesc: "Test your knowledge. Enter a topic to generate a custom challenge.",
        startBtn: "Start Challenge",
        constructing: "Constructing Challenge",
        quizComplete: "Quiz Completed",
        tryAnother: "Try Another Topic",
        addMoreQ: "+10 Questions",
        nextQuestion: "Next Question",
        finish: "Finish Challenge",
        aiInsight: "AI Insight",
        lifelines: "Lifelines",
        hint: "Hint",
        fiftyFifty: "50/50",
        chatPlaceholder: "Ask anything...",
        chatTitle: "Nexus AI Assistant",
        chatDesc: "Your personal intelligence multiplier.",
        learnTitle: "Cosmos Learning Hub",
        learnDesc: "Generate curated study plans and find free resources.",
        generatePlan: "Generate Study Plan",
        watchVideo: "Watch Now",
        module: "Module",
        webSearch: "Web Search",
        deepThink: "Deep Reasoning",
        styleLabel: "Artistic Style",
        vaultTitle: "Idea Vault",
        vaultDesc: "Capture and refine your thoughts with AI assistance.",
        newNote: "New Entry",
        refineNote: "Refine with AI",
        saveNote: "Save Entry",
        mathTitle: "Infinity Math",
        mathDesc: "Master mathematics from foundational basics to advanced calculus.",
        codeTitle: "Code Nexus",
        codeDesc: "Learn programming syntax and logic with AI-generated curriculum.",
        beginner: "Beginner",
        intermediate: "Intermediate",
        advanced: "Advanced",
        generateRoadmap: "Generate Roadmap",
        mathConcept: "Concept Explanation",
        skillTitle: "Skill Forge",
        skillDesc: "Advanced simulation training for soft skills and logic.",
        startSimulation: "Start Simulation",
        evaluate: "Evaluate Response"
    },
    bn: {
        dashboard: "কমান্ড সেন্টার",
        neuroMap: "নিউরো গ্রাফ",
        mindMeld: "মাইন্ড মেল্ড",
        visionLab: "ভিশন ল্যাব",
        quantumQuiz: "কোয়ান্টাম কুইজ",
        nexusChat: "নেক্সাস চ্যাট",
        cosmosLearn: "কসমস লার্ন",
        ideaVault: "আইডিয়া ভল্ট",
        mathPath: "ইনফিনিটি ম্যাথ",
        skillForge: "স্কিল ফোর্জ",
        codeNexus: "কোড নেক্সাস",
        sessions: "সেশন সম্পন্ন",
        concepts: "ধারণা ম্যাপ করা হয়েছে",
        debateTime: "তর্ক সময়",
        quizXp: "কুইজ এক্সপি",
        welcome: "নিউরাল ইন্টারফেস প্রস্তুত",
        welcomeSub: "আপনার জ্ঞানীয় যাত্রা এখন শুরু হচ্ছে।",
        systemStatus: "সিস্টেম স্ট্যাটাস",
        expandGraph: "নলেজ গ্রাফ প্রসারিত করুন",
        resetApp: "অ্যাপ রিসেট করুন",
        startTopic: "একটি বিষয় দিয়ে শুরু করুন...",
        addConcept: "ধারণা যোগ করুন...",
        expandNode: "এই নোড প্রসারিত করুন",
        selectPersona: "ব্যক্তিত্ব নির্বাচন করুন",
        liveLink: "লাইভ লিংক সক্রিয়",
        initLink: "লিংক শুরু করুন",
        listening: "এআই শুনছে। স্পষ্ট করে কথা বলুন।",
        connectToStart: "শুরু করতে একটি ব্যক্তিত্ব নির্বাচন করুন এবং সংযোগ করুন।",
        visualGen: "ভিজ্যুয়াল রূপক জেনারেটর",
        visualDesc: "বিমূর্ত তত্ত্বগুলিকে বাস্তব দৃশ্যে রূপান্তর করুন।",
        conceptLabel: "ভিজুয়ালাইজ করার ধারণা",
        generateBtn: "ভিজুয়ালাইজেশন তৈরি করুন",
        quizTitle: "কোয়ান্টাম কুইজ",
        quizDesc: "আপনার জ্ঞান পরীক্ষা করুন। একটি কাস্টম চ্যালেঞ্জ তৈরি করতে একটি বিষয় লিখুন।",
        startBtn: "চ্যালেঞ্জ শুরু করুন",
        constructing: "চ্যালেঞ্জ তৈরি করা হচ্ছে",
        quizComplete: "কুইজ সম্পন্ন হয়েছে",
        tryAnother: "অন্য বিষয় চেষ্টা করুন",
        addMoreQ: "+১০ প্রশ্ন",
        nextQuestion: "পরবর্তী প্রশ্ন",
        finish: "শেষ করুন",
        aiInsight: "এআই অন্তর্দৃষ্টি",
        lifelines: "লাইফলাইন",
        hint: "ইঙ্গিত",
        fiftyFifty: "৫০/৫০",
        chatPlaceholder: "যেকোনো কিছু জিজ্ঞাসা করুন...",
        chatTitle: "নেক্সাস এআই অ্যাসিস্ট্যান্ট",
        chatDesc: "আপনার ব্যক্তিগত বুদ্ধিমত্তা সহকারী।",
        learnTitle: "কসমস লার্নিং হাব",
        learnDesc: "কাস্টম স্টাডি প্ল্যান এবং বিনামূল্যে রিসোর্স খুঁজুন।",
        generatePlan: "স্টাডি প্ল্যান তৈরি করুন",
        watchVideo: "এখন দেখুন",
        module: "মডিউল",
        webSearch: "ওয়েব সার্চ",
        deepThink: "গভীর চিন্তন",
        styleLabel: "শৈলী",
        vaultTitle: "আইডিয়া ভল্ট",
        vaultDesc: "আপনার চিন্তাগুলি সংরক্ষণ করুন এবং এআই দিয়ে উন্নত করুন।",
        newNote: "নতুন নোট",
        refineNote: "এআই রিফাইন",
        saveNote: "সংরক্ষণ করুন",
        mathTitle: "ইনফিনিটি ম্যাথ",
        mathDesc: "গণিতে দক্ষতা অর্জন করুন, প্রাথমিক থেকে উচ্চতর পর্যন্ত।",
        codeTitle: "কোড নেক্সাস",
        codeDesc: "এআই পাঠ্যক্রমের সাথে প্রোগ্রামিং সিনট্যাক্স এবং যুক্তি শিখুন।",
        beginner: "নতুন",
        intermediate: "মাঝারি",
        advanced: "উন্নত",
        generateRoadmap: "রোডম্যাপ তৈরি করুন",
        mathConcept: "ধারণা ব্যাখ্যা",
        skillTitle: "স্কিল ফোর্জ",
        skillDesc: "দক্ষতা এবং যুক্তির জন্য উন্নত সিমুলেশন প্রশিক্ষণ।",
        startSimulation: "সিমুলেশন শুরু করুন",
        evaluate: "মূল্যায়ন করুন"
    },
    es: {
        dashboard: "Centro de Mando",
        neuroMap: "Neuro Gráfico",
        mindMeld: "Fusión Mental",
        visionLab: "Lab. Visión",
        quantumQuiz: "Cuestionario Cuántico",
        nexusChat: "Chat Nexus",
        cosmosLearn: "Cosmos Educa",
        ideaVault: "Bóveda de Ideas",
        mathPath: "Matemáticas Infinitas",
        skillForge: "Forja de Habilidades",
        codeNexus: "Nexo de Código",
        sessions: "Sesiones",
        concepts: "Conceptos",
        debateTime: "Tiempo Debate",
        quizXp: "XP Prueba",
        welcome: "Interfaz Neural Lista",
        welcomeSub: "Tu viaje cognitivo comienza ahora.",
        systemStatus: "Estado del Sistema",
        expandGraph: "Expandir Gráfico",
        resetApp: "Restablecer App",
        startTopic: "Empieza con un tema...",
        addConcept: "Añadir concepto...",
        expandNode: "Expandir Nodo",
        selectPersona: "Seleccionar Persona",
        liveLink: "Enlace En Vivo",
        initLink: "Iniciar Enlace",
        listening: "La IA está escuchando. Habla claro.",
        connectToStart: "Selecciona una persona para comenzar.",
        visualGen: "Generador de Metáforas",
        visualDesc: "Convierte teorías abstractas en arte visual.",
        conceptLabel: "Concepto a Visualizar",
        generateBtn: "Generar Visualización",
        quizTitle: "Cuestionario Cuántico",
        quizDesc: "Pon a prueba tus conocimientos. Introduce un tema.",
        startBtn: "Iniciar Desafío",
        constructing: "Construyendo Desafío",
        quizComplete: "Cuestionario Completado",
        tryAnother: "Probar Otro Tema",
        addMoreQ: "+10 Preguntas",
        nextQuestion: "Siguiente Pregunta",
        finish: "Terminar",
        aiInsight: "Perspectiva IA",
        lifelines: "Ayudas",
        hint: "Pista",
        fiftyFifty: "50/50",
        chatPlaceholder: "Pregunta lo que sea...",
        chatTitle: "Asistente Nexus",
        chatDesc: "Tu multiplicador de inteligencia personal.",
        learnTitle: "Centro Cosmos",
        learnDesc: "Genera planes de estudio y recursos gratuitos.",
        generatePlan: "Generar Plan",
        watchVideo: "Ver Ahora",
        module: "Módulo",
        webSearch: "Buscar en Web",
        deepThink: "Razonamiento Profundo",
        styleLabel: "Estilo Artístico",
        vaultTitle: "Bóveda de Ideas",
        vaultDesc: "Captura y refina tus pensamientos.",
        newNote: "Nueva Nota",
        refineNote: "Refinar con IA",
        saveNote: "Guardar",
        mathTitle: "Matemáticas Infinitas",
        mathDesc: "Domina las matemáticas desde lo básico hasta lo avanzado.",
        codeTitle: "Nexo de Código",
        codeDesc: "Aprende sintaxis y lógica de programación con IA.",
        beginner: "Principiante",
        intermediate: "Intermedio",
        advanced: "Avanzado",
        generateRoadmap: "Generar Ruta",
        mathConcept: "Explicación del Concepto",
        skillTitle: "Forja de Habilidades",
        skillDesc: "Entrenamiento avanzado de simulación para habilidades blandas.",
        startSimulation: "Iniciar Simulación",
        evaluate: "Evaluar Respuesta"
    },
    fr: {
        dashboard: "Centre de Commande",
        neuroMap: "Neuro Graphe",
        mindMeld: "Fusion Mentale",
        visionLab: "Labo Vision",
        quantumQuiz: "Quiz Quantique",
        nexusChat: "Nexus Chat",
        cosmosLearn: "Cosmos Études",
        ideaVault: "Coffre à Idées",
        mathPath: "Maths Infinies",
        skillForge: "Forge de Compétences",
        codeNexus: "Nexus Code",
        sessions: "Sessions",
        concepts: "Concepts",
        debateTime: "Temps Débat",
        quizXp: "XP Quiz",
        welcome: "Interface Neurale Prête",
        welcomeSub: "Votre voyage cognitif commence maintenant.",
        systemStatus: "État du Système",
        expandGraph: "Étendre le Graphe",
        resetApp: "Réinitialiser",
        startTopic: "Commencez par un sujet...",
        addConcept: "Ajouter concept...",
        expandNode: "Étendre ce Nœud",
        selectPersona: "Choisir Persona",
        liveLink: "Lien En Direct",
        initLink: "Initialiser Lien",
        listening: "L'IA écoute. Parlez clairement.",
        connectToStart: "Sélectionnez un persona pour commencer.",
        visualGen: "Générateur de Métaphores",
        visualDesc: "Convertissez des théories abstraites en art visuel.",
        conceptLabel: "Concept à Visualiser",
        generateBtn: "Générer Visualisation",
        quizTitle: "Quiz Quantique",
        quizDesc: "Testez vos connaissances. Entrez un sujet.",
        startBtn: "Lancer Défi",
        constructing: "Construction du Défi",
        quizComplete: "Quiz Terminé",
        tryAnother: "Autre Sujet",
        addMoreQ: "+10 Questions",
        nextQuestion: "Question Suivante",
        finish: "Terminer",
        aiInsight: "Aperçu IA",
        lifelines: "Jokers",
        hint: "Indice",
        fiftyFifty: "50/50",
        chatPlaceholder: "Demandez n'importe quoi...",
        chatTitle: "Assistant Nexus",
        chatDesc: "Votre multiplicateur d'intelligence personnel.",
        learnTitle: "Centre Cosmos",
        learnDesc: "Plans d'étude et ressources gratuites.",
        generatePlan: "Créer un Plan",
        watchVideo: "Regarder",
        module: "Module",
        webSearch: "Recherche Web",
        deepThink: "Raisonnement Profond",
        styleLabel: "Style Artistique",
        vaultTitle: "Coffre à Idées",
        vaultDesc: "Capturez et affinez vos pensées.",
        newNote: "Nouvelle Note",
        refineNote: "Affiner avec IA",
        saveNote: "Enregistrer",
        mathTitle: "Maths Infinies",
        mathDesc: "Maîtrisez les mathématiques, des bases aux niveaux avancés.",
        codeTitle: "Nexus Code",
        codeDesc: "Apprenez la syntaxe et la logique de programmation avec l'IA.",
        beginner: "Débutant",
        intermediate: "Intermédiaire",
        advanced: "Avancé",
        generateRoadmap: "Générer la Feuille de Route",
        mathConcept: "Explication du Concept",
        skillTitle: "Forge de Compétences",
        skillDesc: "Formation par simulation pour les compétences.",
        startSimulation: "Lancer Simulation",
        evaluate: "Évaluer Réponse"
    },
    hi: {
        dashboard: "कमांड सेंटर",
        neuroMap: "न्यूरो ग्राफ",
        mindMeld: "माइंड मेल्ड",
        visionLab: "विज़न लैब",
        quantumQuiz: "क्वांटम क्विज़",
        nexusChat: "नेक्सस चैट",
        cosmosLearn: "कॉसमॉस लर्न",
        ideaVault: "आइडिया वॉल्ट",
        mathPath: "इन्फिनिटी गणित",
        skillForge: "कौशल फोर्ज",
        codeNexus: "कोड नेक्सस",
        sessions: "सत्र पूरे हुए",
        concepts: "अवधारणाएं",
        debateTime: "बहस का समय",
        quizXp: "क्विज़ XP",
        welcome: "न्यूरल इंटरफ़ेस तैयार",
        welcomeSub: "आपकी संज्ञानात्मक यात्रा अब शुरू होती है।",
        systemStatus: "सिस्टम स्थिति",
        expandGraph: "ज्ञान ग्राफ का विस्तार करें",
        resetApp: "ऐप रीसेट करें",
        startTopic: "एक विषय के साथ शुरू करें...",
        addConcept: "अवधारणा जोड़ें...",
        expandNode: "इस नोड का विस्तार करें",
        selectPersona: " व्यक्तित्व चुनें",
        liveLink: "लाइव लिंक सक्रिय",
        initLink: "लिंक प्रारंभ करें",
        listening: "AI सुन रहा है। स्पष्ट बोलें।",
        connectToStart: "शुरू करने के लिए एक व्यक्तित्व चुनें और कनेक्ट करें।",
        visualGen: "दृश्य रूपक जनरेटर",
        visualDesc: "अमूर्त सिद्धांतों को ठोस दृश्य कला में बदलें।",
        conceptLabel: "विज़ुअलाइज़ करने की अवधारणा",
        generateBtn: "विज़ुअलाइज़ेशन उत्पन्न करें",
        quizTitle: "क्वांटम क्विज़",
        quizDesc: "अपने ज्ञान का परीक्षण करें। एक कस्टम चुनौती बनाने के लिए एक विषय दर्ज करें।",
        startBtn: "चुनौती शुरू करें",
        constructing: "चुनौती का निर्माण",
        quizComplete: "क्विज़ पूरा हुआ",
        tryAnother: "दूसरा विषय आज़माएं",
        addMoreQ: "+10 प्रश्न",
        nextQuestion: "अगला प्रश्न",
        finish: "समाप्त करें",
        aiInsight: "AI अंतर्दृष्टि",
        lifelines: "लाइफলাইন",
        hint: "संकेत",
        fiftyFifty: "50/50",
        chatPlaceholder: "कुछ भी पूछें...",
        chatTitle: "नेक्सस AI",
        chatDesc: "आपका व्यक्तिगत खुफिया गुणक।",
        learnTitle: "कॉसमॉस लर्निंग हब",
        learnDesc: "अध्ययन योजनाएं और मुफ्त संसाधन खोजें।",
        generatePlan: "योजना बनाएं",
        watchVideo: "अभी देखें",
        module: "मॉड्यूल",
        webSearch: "वेब खोज",
        deepThink: "गहरा विचार",
        styleLabel: "कलात्मक शैली",
        vaultTitle: "आइडिया वॉल्ट",
        vaultDesc: "अपने विचार कैप्चर करें और AI के साथ सुधारें।",
        newNote: "नई प्रविष्टि",
        refineNote: "AI के साथ परिष्कृत करें",
        saveNote: "सहेजें",
        mathTitle: "इन्फिनिटी गणित",
        mathDesc: "बुनियादी बातों से लेकर उन्नत तक गणित में महारत हासिल करें।",
        codeTitle: "कोड नेक्सस",
        codeDesc: "AI के साथ प्रोग्रामिंग सिंटैक्स और लॉजिक सीखें।",
        beginner: "शुरुआत करने वाला",
        intermediate: "मध्यवर्ती",
        advanced: "उन्नत",
        generateRoadmap: "रोडमैप बनाएं",
        mathConcept: "अवधारणा स्पष्टीकरण",
        skillTitle: "कौशल फोर्ज",
        skillDesc: "सॉफ्ट स्किल्स और लॉजिक के लिए उन्नत सिमुलेशन प्रशिक्षण।",
        startSimulation: "सिमुलेशन शुरू करें",
        evaluate: "प्रतिक्रिया का मूल्यांकन करें"
    }
};
